name: GitHub Actions Docker Push

run-name: ${{ github.actor }} is pushing German images to Docker.

on: [push]

jobs:
  build_docker_image_address_nobase_de:
    runs-on: ubuntu-latest
    name: Push image using an German address model (no base)

    steps:
    - uses: actions/checkout@v3
    - name: Move address model
      run: rsync -a ./AutomationService/ExampleBodies/ExampleModels/address_nobase_de/* ./AutomationService/AutomationServiceBackend/data/model/
    - name: Build the Docker image
      run: docker compose -f AutomationService/docker-compose_full-qanary-example-HTWK-stardog.yml build automation_component
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest qanary/qanary-component-ner-automl-pretrained-address-nobase-de:latest
    - name: Tag fixed version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest "qanary/qanary-component-ner-automl-pretrained-address-nobase-de:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push qanary/qanary-component-ner-automl-pretrained-address-nobase-de:latest
    - name: Push fixed docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "qanary/qanary-component-ner-automl-pretrained-address-nobase-de:${{ github.ref_name }}"

  build_docker_image_address_spacy_de:
    runs-on: ubuntu-latest
    name: Push image using an German address model (spacy)

    steps:
    - uses: actions/checkout@v3
    - name: Move address model
      run: rsync -a ./AutomationService/ExampleBodies/ExampleModels/address_spacy_de/* ./AutomationService/AutomationServiceBackend/data/model/
    - name: Build the Docker image
      run: docker compose -f AutomationService/docker-compose_full-qanary-example-HTWK-stardog.yml build automation_component
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest qanary/qanary-component-ner-automl-pretrained-address-spacy-de:latest
    - name: Tag fixed version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest "qanary/qanary-component-ner-automl-pretrained-address-spacy-de:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push qanary/qanary-component-ner-automl-pretrained-address-spacy-de:latest
    - name: Push fixed docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "qanary/qanary-component-ner-automl-pretrained-address-spacy-de:${{ github.ref_name }}"

  build_docker_image_name_nobase_de:
    runs-on: ubuntu-latest
    name: Push image using an German name model (no base)

    steps:
    - uses: actions/checkout@v3
    - name: Move name model
      run: rsync -a ./AutomationService/ExampleBodies/ExampleModels/name_nobase_de/* ./AutomationService/AutomationServiceBackend/data/model/
    - name: Build the Docker image
      run: docker compose -f AutomationService/docker-compose_full-qanary-example-HTWK-stardog.yml build automation_component
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest qanary/qanary-component-ner-automl-pretrained-name-nobase-de:latest
    - name: Tag fixed version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest "qanary/qanary-component-ner-automl-pretrained-name-nobase-de:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push qanary/qanary-component-ner-automl-pretrained-name-nobase-de:latest
    - name: Push fixed docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "qanary/qanary-component-ner-automl-pretrained-name-nobase-de:${{ github.ref_name }}"

  build_docker_image_name_spacy_de:
    runs-on: ubuntu-latest
    name: Push image using an German name model (spacy)

    steps:
    - uses: actions/checkout@v3
    - name: Move name model
      run: rsync -a ./AutomationService/ExampleBodies/ExampleModels/name_spacy_de/* ./AutomationService/AutomationServiceBackend/data/model/
    - name: Build the Docker image
      run: docker compose -f AutomationService/docker-compose_full-qanary-example-HTWK-stardog.yml build automation_component
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest qanary/qanary-component-ner-automl-pretrained-name-spacy-de:latest
    - name: Tag fixed version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag automation-component-container:latest "qanary/qanary-component-ner-automl-pretrained-name-spacy-de:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push qanary/qanary-component-ner-automl-pretrained-name-spacy-de:latest
    - name: Push fixed docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "qanary/qanary-component-ner-automl-pretrained-name-spacy-de:${{ github.ref_name }}"
