name: GitHub Actions Asciidoc Transfer

run-name: ${{ github.actor }} is generating a README in Markdown.

on: [push]

jobs:

  generate_readme:
    name: Create Markdown Readme
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sudo apt-get install asciidoc pandoc 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Remove characters / phrases that cannot be interpreted in the asciidoc - markdown conversion
        run: |
          sed -i "s/\[.lead\]/ /g" ./README.adoc 
          sed -i "s/>/ /g" ./README.adoc 
      - name: Start ASCIIDOC conversion
        run: | 
          asciidoc -b docbook README.adoc
          cat ./README.xml
          pandoc -f docbook -t markdown_strict ./README.xml -o ./READMEmd.md
          sed -i '1i# Automation Service \n' READMEmd.md 
      - name: Upload generated Readme for job 1 generate_readme
        uses: actions/upload-artifact@v3
        with:
          name: readme
          path: READMEmd.md

  push_readme:
    name: Push new Readme
    needs: generate_readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download readme result from job 1 generate_readme
        uses: actions/download-artifact@v3
        with:
          name: readme
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add READMEmd.md
          git commit -m "Actions Generated Readme"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_docker_image_address_nobase:
    name: Build image with baseless address model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: List all folders
    - name: Move address model
      run: mv ./AutomationService/ExampleBodies/ExampleModels/address_model_nobase/ ./AutomationService/AutomationServiceBackend/data/model/
    - name: Build the Docker image
      run: docker compose -f AutomationService/docker-compose_full-qanary-example-HTWK-stardog.yml build automation_component
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      run: docker tag automation-component-container:latest qanary/qanary-component-ner-automl-pretrained-address-nobase:0.1.0
    - name: Push docker image
      run: docker push qanary/qanary-component-ner-automl-pretrained-address-nobase:0.1.0